Update test_pipeline.yml

diff --git a/.github/workflows/test_pipeline.yml b/.github/workflows/test_pipeline.yml
--- a/.github/workflows/test_pipeline.yml
+++ b/.github/workflows/test_pipeline.yml
@@ -36,7 +36,7 @@ jobs:
           run: |
             BRANCH_NAME="${{ github.event.inputs.branch-name }}"
             echo $BRANCH_NAME | grep -E "^RUNTREQ-[0-9]{4}$" -q
-            [ $? != 0 ] && { echo "Invalid Branch name";exit 1; }
+            [ $? != 0 ] &&  echo "Invalid Branch name";exit 1; 
         
         - name: Check user email
           run: |
