Update test_pipeline.yml

diff --git a/.github/workflows/test_pipeline.yml b/.github/workflows/test_pipeline.yml
--- a/.github/workflows/test_pipeline.yml
+++ b/.github/workflows/test_pipeline.yml
@@ -37,14 +37,14 @@ jobs:
           run: |
             BRANCH_NAME="${{ github.event.inputs.branch-name }}"
             echo $BRANCH_NAME | grep -E "^RUNTREQ-[0-9]{4}$" -q
-            [ $? != 0 ] && { echo "Invalid Branch name";exit 1; } || echo "Valid request" 
+            [ $? != 0 ] && { echo "Invalid Branch name";exit 1; } || echo -e "\033[0;32mValid request\033[0m"
         
         - name: Check user email
           shell: bash {0}
           run: |
             USER_EMAIL="${{ github.event.inputs.user-email }}"
             echo $USER_EMAIL | grep -E '[[:alnum:]"[[:alnum:]%&'"'"'*+/=?`{|}~^.-]+@[[:alnum:]_-]+(\.[[:alnum:]_-]+)*\.[[:alpha:]]{2,6}' -q
-            [ $? != 0 ] && { echo "Invalid Email name";exit 1; } || echo "Valid email"
+            [ $? != 0 ] && { echo "Invalid Email name";exit 1; } || echo -e "\033[0;32mValid email\033[0m"
 
     perform-action:
       needs: check-details
@@ -67,7 +67,7 @@ jobs:
             USER_EMAIL="${{ github.event.inputs.user-email }}"
             echo "Email to check in file $USER_EMAIL"
             grep -qi $USER_EMAIL ./example.tf 
-            [ $? = 0 ] && { echo "Email alreay configured";exit 1; } || echo "Going forward"
+            [ $? = 0 ] && { echo -e "\033[0;31mEmail alreay configured\033[0m";exit 1; } || echo -e "\033[0;32mGoinf Forward\033[0m"
 
         - name: Install requirements
           run: pip install -r requirements.txt
