Update test_pipeline.yml

diff --git a/.github/workflows/test_pipeline.yml b/.github/workflows/test_pipeline.yml
--- a/.github/workflows/test_pipeline.yml
+++ b/.github/workflows/test_pipeline.yml
@@ -36,10 +36,10 @@ jobs:
           run: |
             BRANCH_NAME="${{ github.event.inputs.branch-name }}"
             echo $BRANCH_NAME | grep -E "^RUNTREQ-[0-9]{4}$" -q
-            [ $? != 0 ] &&  echo "Invalid Branch name";exit 1; 
+            [ $? != 0 ] && { echo "Invalid Branch name";exit 1; } || echo "Valid request" 
         
         - name: Check user email
           run: |
             USER_EMAIL="${{ github.event.inputs.user-email }}"
             echo $USER_EMAIL | grep -E '[[:alnum:]"[[:alnum:]%&'"'"'*+/=?`{|}~^.-]+@[[:alnum:]_-]+(\.[[:alnum:]_-]+)*\.[[:alpha:]]{2,6}' -q
-            [ $? != 0 ] && { echo "Invalid Email name";exit 1; } || echo "hello"
+            [ $? != 0 ] && { echo "Invalid Email name";exit 1; } || echo "Valid email"
